name: Project test & build
on:
  push:
    branches: [ myDev ]
  pull_request:
    branches: [ myDev ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install modules ğŸ”§
        run: npm install

      - name: build production project ğŸ”¨
        run: npm run build:prod

      - name: linting ts ğŸ”¨
        run: npm run lint:ts

      - name: linting scss ğŸ”¨
        run: npm run lint:scss

      - name: unit testing ğŸ”¨
        run: npm run test:unit
        